compliant:
  regex: "\\b(?:compliant|noncompliant|noncompliance|poor compliance)\\b"
  privileging_score: 2
  stigmatizing_score: 1.5
  valence: "ambiguous"
engaged:
  regex: "\\b(?:engaged|engagement|engages)\\b"
  privileging_score: 2.3
  stigmatizing_score: 5
  valence: "ambiguous"
managed:
  regex: "\\b(?:managed|bmanagement|bmanages)\\b"
  privileging_score: 2.3
  stigmatizing_score: 5
  valence: "privileging"
involved:
  regex: "\\b(?:involved|binvolvement)\\b"
  privileging_score: 2.3
  stigmatizing_score: 5
  valence: "neutral"
pleasant:
  regex: "\\b(?:pleasant|unpleasant)\\b"
  privileging_score: 1.6
  stigmatizing_score: 1
  valence: "undefined"
dressed:
  regex: "\\b(?:appropriately dressed|well dressed)\\b"
  privileging_score: 1.6
  stigmatizing_score: 5
  valence: "privileging"
groomed:
  regex: "\\b(?:groomed| well groomed| appropriately groomed|ungroomed)\\b"
  privileging_score: 1.6
  stigmatizing_score: 1.8
  valence: "ambiguous"
happy:
  regex: "\\bhappy\\b"
  privileging_score: 1
  stigmatizing_score: 5
  valence: "ambiguous"
friendly:
  regex: "\\bfriendly\\b"
  privileging_score: 1.3
  stigmatizing_score: 5
  valence: "undefined"
cordial:
  regex: "\\bcordial\\b"
  privileging_score: 1.6
  stigmatizing_score: 5
  valence: "undefined"
motivated:
  regex: "\\b(?:motivated|unmotivated)\\b"
  privileging_score: 1.6
  stigmatizing_score: 1
  valence: "undefined"
charming:
  regex: "\\bcharming\\b"
  privileging_score: 1
  stigmatizing_score: 5
  valence: "undefined"
inspiring:
  regex: "\\binspiring\\b"
  privileging_score: 1.6
  stigmatizing_score: 5
  valence: "neutral"
kind:
  regex: "\\bkind\\b"
  privileging_score: 1.3
  stigmatizing_score: 5
  valence: "neutral"
good insight:
  regex: "\\bgood insight\\b"
  privileging_score: 2.3
  stigmatizing_score: 5
  valence: "privileging"
knowledgeable:
  regex: "\\bknowledgeable\\b"
  privileging_score: 2.3
  stigmatizing_score: 5
  valence: "privileging"
informed:
  regex: "\\b(?:informed|uninformed)\\b"
  privileging_score: 2.3
  stigmatizing_score: 1
  valence: "undefined"
skilled:
  regex: "\\b(?:skilled|unskilled)\\b"
  privileging_score: 2.3
  stigmatizing_score: 1.2
  valence: "undefined"
support_system:
  regex: "\\bsupport system\\b"
  privileging_score: 2.6
  stigmatizing_score: 5
  valence: "privileging"
employed:
  regex: "\\bemployed\\b"
  privileging_score: 3
  stigmatizing_score: 5
  valence: "neutral"
healthy:
  regex: "\\bhealthy\\b"
  privileging_score: 2
  stigmatizing_score: 5
  valence: "ambiguous"
disciplined:
  regex: "\\bdisciplined\\b"
  privileging_score: 1
  stigmatizing_score: 5
  valence: "undefined"
active:
  regex: "\\b(?:active|inactive)\\b"
  privileging_score: 3
  stigmatizing_score: 2.6
  valence: "undefined"
educated:
  regex: "\\beducated\\b"
  privileging_score: 1.6
  stigmatizing_score: 5
  valence: "neutral"
willing:
  regex: "\\b(?:willing|unwilling)\\b"
  privileging_score: 2
  stigmatizing_score: 1.2
  valence: "ambiguous"
adamant:
  regex: "\\b(?:adamant|adamantly)\\b"
  privileging_score: 2.8
  stigmatizing_score: 5
  valence: "undefined"
aggressive:
  regex: "\\baggressive\\b"
  privileging_score: 5
  stigmatizing_score: 2
  valence: "ambiguous"
agitated:
  regex: "\\bagitated\\b"
  privileging_score: 5
  stigmatizing_score: 2.4
  valence: "ambiguous"
angry:
  regex: "\\bangry\\b"
  privileging_score: 5
  stigmatizing_score: 2
  valence: "stigmatizing"
anxious:
  regex: "\\b(?:anxious|anxiety)\\b"
  privileging_score: 5
  stigmatizing_score: 2.8
  valence: "undefined"
apparently:
  regex: "\\bapparently\\b"
  privileging_score: 5
  stigmatizing_score: 2.8
  valence: "undefined"
appears_to_be:
  regex: "\\bappears to be\\b"
  privileging_score: 5
  stigmatizing_score: 3
  valence: "undefined"
argumentative:
  regex: "\\bargumentative\\b"
  privileging_score: 5
  stigmatizing_score: 1
  valence: "stigmatizing"
believes:
  regex: "\\bbelieves\\b"
  privileging_score: 5
  stigmatizing_score: 3
  valence: "undefined"
challenging:
  regex: "\\bchallenging\\b"
  privileging_score: 5
  stigmatizing_score: 1.6
  valence: "ambiguous"
claim:
  regex: "\\b(?:claims|claiming)\\b"
  score: 2.6
  valence: "undefined"
combative:
  regex: "\\bcombative\\b"
  privileging_score: 5
  stigmatizing_score: 2
  valence: "ambiguous"
complain:
  regex: "\\b(?:complains|complained|complaining)\\b"
  privileging_score: 5
  stigmatizing_score: 3
  valence: "undefined"
confront:
  regex: "\\bconfront\\b"
  privileging_score: 5
  stigmatizing_score: 1.6
  valence: "undefined"
defensive:
  regex: "\\bdefensive\\b"
  privileging_score: 5
  stigmatizing_score: 2
  valence: "undefined"
deny:
  regex: "\\b(?:denies|denied|denying|in denial)\\b"
  privileging_score: 5
  stigmatizing_score: 1.4
  valence: "undefined"
difficult:
  regex: "\\bdifficult\\b"
  privileging_score: 5
  stigmatizing_score: 1.4
  valence: "neutral"
dirty:
  regex: "\\bdirty\\b"
  privileging_score: 5
  stigmatizing_score: 1.6
  valence: "neutral"
endorse:
  regex: "\\b(?:endorsing|endorsed|endorse)\\b"
  privileging_score: 5
  stigmatizing_score: 3.4
  valence: "undefined"
exaggerate:
  regex: "\\bexaggerate\\b"
  privileging_score: 5
  stigmatizing_score: 1.2
  valence: "undefined"
fail:
  regex: "\\bfail\\b"
  privileging_score: 5
  stigmatizing_score: 1
  valence: "neutral"
hysterical:
  regex: "\\bhysterical\\b"
  privileging_score: 5
  stigmatizing_score: 1.2
  valence: "stigmatizing"
insist:
  regex: "\\b(?:insist|insisting|insists)\\b"
  privileging_score: 5
  stigmatizing_score: 2
  valence: "stigmatizing"
irritable:
  regex: "\\birritable\\b"
  privileging_score: 5
  stigmatizing_score: 2.2
  valence: "ambiguous"
lazy:
  regex: "\\blazy\\b"
  privileging_score: 5
  stigmatizing_score: 1
  valence: "neutral"
adherence:
  regex: "\\b(?:nonadherent|non-adherent|adherent)\\b"
  privileging_score: 3.3
  stigmatizing_score: 2.8
  valence: "neutral"
noncooperative:
  regex: "\\b(?:noncooperative|not cooperate)\\b"
  privileging_score: 5
  stigmatizing_score: 1.6
  valence: "undefined"
refuse:
  regex: "\\b(?:refuse|refuses|refused)\\b"
  privileging_score: 5
  stigmatizing_score: 2
  valence: "ambiguous"
reports:
  regex: "\\b(?:reports|reporting|reportedly)\\b"
  privileging_score: 5
  stigmatizing_score: 3
  valence: "undefined"
resist:
  regex: "\\bresist\\b"
  privileging_score: 5
  stigmatizing_score: 1.6
  valence: "neutral"
say:
  regex: "\\b(?:says|saying)\\b"
  privileging_score: 5
  stigmatizing_score: 2.4
  valence: "undefined"
sedentary:
  regex: "\\bsedentary\\b"
  privileging_score: 5
  stigmatizing_score: 2.4
  valence: "undefined"
supposedly:
  regex: "\\bsupposedly\\b"
  privileging_score: 5
  stigmatizing_score: 1
  valence: "stigmatizing"
tell:
  regex: "\\b(?:tells me|tells|told)\\b"
  privileging_score: 5
  stigmatizing_score: 3.2
  valence: "undefined"
undisciplined:
  regex: "\\bundisciplined\\b"
  privileging_score: 5
  stigmatizing_score: 1
  valence: "undefined"
unkempt:
  regex: "\\bunkempt\\b"
  privileging_score: 5
  stigmatizing_score: 2
  valence: "undefined"
unreliable:
  regex: "\\bunreliable\\b"
  privileging_score: 5
  stigmatizing_score: 1.2
  valence: "neutral"
quotations:
  regex: '"[\\"“”][^"\\"“”]+[\\"“”]"'
  privileging_score: 5
  stigmatizing_score: 1.4
  valence: "undefined"