name: CI

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
    paths:
      - "docs/**"
      - "medsplex/**"
      - "tests/**"
      - "pyproject.toml"
      - ".github/workflows/tests.yml"
      - ".pre-commit-config.yaml"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Linting code
        uses: astral-sh/ruff-action@v3

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Run tests
        run: |
          pytest
